name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - dev
jobs:
    build:
        runs-on: "ubuntu-latest" 
        steps: 
           - name: Кнонирование
             uses: actions/checkout@v4
           - name: "Вывод test"
             run: echo Hello
             
